name: ask-stacker-name
description: Plugin to add capacity to hello stacker app to ask stacker name before say hello
types:
  - app
hooks:
  - type: edit
    trigger: after-render
    path: main.py
    changes:
      - insert:
          line: 0
          value: "import sys\n\n"
          when:
            not-exists: import sys
      - search:
          string: "def say_hello():"
          insert-after:
            snippet: snippets/ask_name_snippet
          when:
            not-exists: print("What is you name stacker?")
      - search:
          string: "Stacker!"
          replace-by:
            value: "{name}!" 
          when:
            not-exists: "{name}!"